#!/bin/sh
. %{_datadir}/java-utils/java-functions
MAIN_CLASS=org.basex.BaseX
BASE_FLAGS="-mx512m"
BASE_JARS="tagsoup xml-commons-resolver lucene-contrib/analyzers lucene-contrib/snowball %{name}-%{version}"
# TODO: add igo
set_jvm
set_classpath $BASE_JARS
set_flags $BASE_FLAGS
run "$@"

